// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVz8Mlp_6kHJo0SUmR_OPMBB1FcA7_1tI',
    appId: '1:759981236251:web:b3471307f9cc403e2618be',
    messagingSenderId: '759981236251',
    projectId: 'deeptaldapp',
    authDomain: 'deeptaldapp.firebaseapp.com',
    storageBucket: 'deeptaldapp.appspot.com',
    measurementId: 'G-SV5SF5L2J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tZPWvHBPn54_ePeyJSGGa5lh7rPwYm0',
    appId: '1:759981236251:android:ec42daffc3611b952618be',
    messagingSenderId: '759981236251',
    projectId: 'deeptaldapp',
    storageBucket: 'deeptaldapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDctxmMhJb7o5W-fbFANkkRbUn4kD0m6X4',
    appId: '1:759981236251:ios:4f44db8e901ef8782618be',
    messagingSenderId: '759981236251',
    projectId: 'deeptaldapp',
    storageBucket: 'deeptaldapp.appspot.com',
    iosBundleId: 'com.example.deepTald',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDctxmMhJb7o5W-fbFANkkRbUn4kD0m6X4',
    appId: '1:759981236251:ios:3a856d057d1c57422618be',
    messagingSenderId: '759981236251',
    projectId: 'deeptaldapp',
    storageBucket: 'deeptaldapp.appspot.com',
    iosBundleId: 'com.example.deepTald.RunnerTests',
  );
}
